// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlxgaoqnnytkpjfgrpii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhseGdhb3Fubnl0a3BqZmdycGlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODc1MjIsImV4cCI6MjA2OTI2MzUyMn0.yGh7ap-FJqi4GzsH6eq57co4SzJGhtgUR86peoiSsyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});